import type { Metadata } from 'next';
import { Courgette } from 'next/font/google';
import './globals.css';

const courgette = Courgette({
  weight: '400',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={courgette.className}>{children}</body>
    </html>
  );
}
